#! /bin/bash

sudo cp config/cmdline.txt /boot
sudo cp config/config.txt /boot
pushd ~
git clone https://github.com/whaleygeek/pyenergenie
git clone https://github.com/whaleygeek/school_mc_demo
git clone https://github.com/whaleygeek/mc_bigbang
git clone https://github.com/whaleygeek/pibakeoff
git clone https://github.com/whaleygeek/guessinggame
git clone https://github.com/whaleygeek/pyws
git clone https://github.com/whaleygeek/pyparsers

