#! /bin/bash

if [ $# -eq 0 ] 
then
  # get all latest files
  git pull
  # now that update script is latest, run update actions
  ./update 1

else
  # put any post-pull update actions here
  pushd ..
  git clone https://github.com/whaleygeek/pyenergenie
  popd

  pushd ../pyenergenie
  git pull
  popd

  pushd ..
  git clone https://github.com/whaleygeek/school_mc_demo
  popd

  pushd ../school_mc_demo
  git pull
  popd

  pushd ..
  git clone https://github.com/whaleygeek/mc_bigbang
  popd

  pushd ../mc_bigbang
  git pull
  popd

  pushd ..
  git clone https://github.com/whaleygeek/pibakeoff
  popd

  pushd ../pibakeoff
  git pull
  popd

  pushd ..
  git clone https://github.com/whaleygeek/guessinggame
  popd

  pushd ../guessinggame
  git pull
  popd

  pushd ..
  git clone https://github.com/whaleygeek/pyws
  popd

  pushd ../pyws
  git pull
  popd

  pushd ..
  git clone https://github.com/whaleygeek/pyparsers
  popd

  pushd ../pyparsers
  git pull
  popd

  echo Update completed      
fi
